// Generated by CoffeeScript 1.10.0
(function() {
  var fill;

  fill = function(container, liquid) {
    if (liquid == null) {
      liquid = "coffee";
    }
    "Filling the " + container + " with " + liquid;
    return module.exports = fill;
  };

}).call(this);
